### ISSUE TITLE
Legality issues

### ISSUE THREAD

**Issue by SamboyCoding** [merlinentert/ravenfield_mods#3]
I would like to point out that by distributing modified copies of Assembly-CSharp.dll, without the express permission of SteelRaven7 for each file, you are infringing upon his rights as a developer as this file contains all of the game's code, which he created. It would be better, perhaps, to use IL patching (for example, Mono.Cecil) to inject modified code into the assembly through an executable file.

**Comment by MilesFM** [comment]
I'm not sure if it falls under fair use or not, but SteelRaven7 hasn't said anything against RF mods like this. Fair point and I think maybe talking to SteelRaven7 and handing the GitHub to him would be the best idea.
