### ISSUE TITLE
RAVENFIELD NOT WORKING!!

### ISSUE THREAD

**Issue by Beast2426** [merlinentert/ravenfield_mods#4]
I DOWNLOADED THE MOD AND PUT THEM IN THE FOLDER AND THEN MY RAVENFIELD WOULD NOT FREAKING WORK AND NOW IM MAD

**Comment by ghost** [comment]
You can reset the game files by verifyng integrity of game files.
More info: https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335

It should also be mentioned that you can mods only for the version they were designed for.
